# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            webBox
tagline:          "the blog"
description:      we are a group of people who love to contribute and 
                  build open-source projects, modern web applications 
                  with modern technologies and great developer conferences.

url:              http://blog.webbox.io
baseurl:          /

author:
  name:           webBox Team
  url:            https://twitter.com/webboxio

paginate:         5

