# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            webBox
tagline:          "the blog"
description:      here, we reveal the secret sauce recipes inside the magical blue box.

url:              http://blog.webbox.io
baseurl:          /

author:
  name:           webBox Team
  url:            https://twitter.com/webboxio

paginate:         5

