# Dependencies
exclude:          [vendor, Rakefile, Gemfile]
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            webBox
tagline:          "the blog"
description:      here, we reveal the secret sauce recipes inside the magical blue box.

url:              http://blog.webbox.io
baseurl:          /

excerpt_separator: "<!-- more -->"
paginate_path:   'page/:num'

author:
  name:           webBox Team
  url:            https://twitter.com/webboxio

paginate:         10

post:
  template:       _templates/_post.txt
  extension:      md

page:
  template:       _templates/_page.txt
  extension:      md

editor:           vim

git:
  branch:         master
